
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 20 10:59:30 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int X = 7;
  public static final int MENOS = 3;
  public static final int EOF = 0;
  public static final int PYC = 6;
  public static final int MAS = 2;
  public static final int NUMERO = 8;
  public static final int ASIG = 5;
  public static final int error = 1;
  public static final int ELEV = 4;
}

