
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 19 17:11:04 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 6;
  public static final int MAS = 2;
  public static final int error = 1;
  public static final int MENOS = 3;
  public static final int DIV = 5;
  public static final int POR = 4;
  public static final int EOF = 0;
}

