
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 27 19:23:31 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 9;
  public static final int MENOS = 3;
  public static final int PD = 8;
  public static final int POR = 4;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int LT = 6;
  public static final int PI = 7;
}

