
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 27 20:44:47 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

