
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 20 10:25:37 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 6;
  public static final int DIVIDE = 5;
  public static final int CP = 9;
  public static final int SUMA = 2;
  public static final int EOF = 0;
  public static final int PYC = 7;
  public static final int NUMERO = 10;
  public static final int MULTIPLICA = 4;
  public static final int error = 1;
  public static final int RESTA = 3;
  public static final int AP = 8;
}

