
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 27 20:12:14 CEST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOUBLE = 3;
  public static final int error = 1;
  public static final int IDENT = 5;
  public static final int EOF = 0;
  public static final int PYC = 4;
  public static final int INT = 2;
}

