
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 20 09:38:16 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 10;
  public static final int INT = 2;
  public static final int IDENT = 8;
  public static final int LONG = 3;
  public static final int BOOLEAN = 7;
  public static final int EOF = 0;
  public static final int PYC = 9;
  public static final int DOUBLE = 5;
  public static final int error = 1;
  public static final int FLOAT = 4;
  public static final int CHAR = 6;
}

